refactor: speed up writing model fields
SysBioChalmers/Human-GEM pull request #393
Opened 2022-06-14 11:35 UTC by edkerk

### Main improvements in this PR:
- refactor:
  - `importYaml` speed improvement, contributing to #387

On my PC, `importYaml('../../model/Human-GEM.yml');` tooks 248 seconds before the change and 168 seconds after the change.

**I hereby confirm that I have:**

- [x] Tested my code on my own computer for running the model
- [x] Selected `develop` as a target branch

2022-06-14 20:36 UTC, mihai-sysbio approved these changes
🦄

2022-06-14 20:40 UTC, edkerk commented
I couldn't stand not fixing the last part. It's now much faster, takes about 12 sec. I don't see room for more improvement.

2022-06-14 21:58 UTC, johan-gson commented on code/io/importYaml.m
> +    fid=fopen(yamlFile);
A bit confusing with yamlFile and yamlFilename - it looks like yamlFilename is the right one, if I look at line 1?

2022-06-14 22:04 UTC, johan-gson requested changes
Just take a look at the yamlFile things. I take it that you tested that it became faster?

2022-06-14 22:04 UTC, johan-gson commented on code/io/importYaml.m
> +    line_raw=readlines(yamlFile');
should this really be yamlFile' ?

2022-06-15 07:59 UTC, edkerk commented on code/io/importYaml.m
> +    fid=fopen(yamlFile);
```suggestion
    fid=fopen(yamlFilename);
```

2022-06-15 08:58 UTC, edkerk commented on code/io/importYaml.m
> +    line_raw=readlines(yamlFile');
```suggestion
    line_raw=readlines(yamlFilename');
```

2022-06-15 08:59 UTC, edkerk commented on code/io/importYaml.m
> +    line_raw=readlines(yamlFile');
Fixed, thanks for noticing!

2022-06-15 10:52 UTC, johan-gson approved these changes
Now it looks better!

2022-06-15 15:50 UTC, edkerk commented
@haowang-bioinfo In f2d5352 I incorporated _similar_ changes as you introduced in #392 (but not exactly the same as it wouldn't match the refactoring that I did). Can you please check that it matches the behaviour that you need?

2022-06-15 22:49 UTC, haowang-bioinfo commented
> @haowang-bioinfo In https://github.com/SysBioChalmers/Human-GEM/commit/f2d5352f108986ef83a0262798e35602b03db20a I incorporated similar changes as you introduced in https://github.com/SysBioChalmers/Human-GEM/pull/392 (but not exactly the same as it wouldn't match the refactoring that I did). Can you please check that it matches the behaviour that you need?

will look into this

2022-06-17 09:00 UTC, mihai-sysbio commented
The `importYaml` function is used in the tests implemented with GH Actions. From the history I see the speedup is from [~5min30s](https://github.com/SysBioChalmers/Human-GEM/runs/6752909441?check_suite_focus=true) down to [~1m30s](https://github.com/SysBioChalmers/Human-GEM/runs/6903361764?check_suite_focus=true). With this confirmed speed improvement and tests passing, I will go ahead and merge this PR.

2022-06-17 09:23 UTC, merged