fix-remove two rxns wrongly annotated with Phe metabolism
SysBioChalmers/Human-GEM pull request #474
Opened 2023-02-09 10:29 UTC by feiranl

### Main improvements in this PR:
* remove **65 more** non-metabolic genes and two rxns, as proposed in #471 

**I hereby confirm that I have:**

- [X] Tested my code on my own computer for running the model
- [X] Selected `develop` as a target branch
*Note: replace [ ] with [X] to check the box. PLEASE DELETE THIS LINE*

2023-02-09 10:55 UTC, mihai-sysbio requested changes
I've spot-checked the gene removal and it seems ok. The actions complain about reaction annotation mismatch - please remove the reactions from `reactions.tsv`. Also as a reminder, all removals should in fact move the entries to the corresponding deprecated identifier tsv files in https://github.com/SysBioChalmers/Human-GEM/tree/main/data/deprecatedIdentifiers

2023-02-09 11:06 UTC, haowang-bioinfo commented
> please remove the reactions from reactions.tsv. Also as a reminder, all removals should in fact move the entries to the corresponding deprecated identifier tsv files

@mihai-sysbio good catch, working on this

2023-02-09 11:22 UTC, mihai-sysbio approved these changes

2023-02-13 08:26 UTC, mihai-sysbio commented
@all-contributors please add @feiranl for bug reports, code, data, project management, research, reviewed pull requests.

2023-02-13 20:00 UTC, haowang-bioinfo approved these changes

2023-02-13 20:01 UTC, merged